# -*- coding: utf-8 -*-
"""Putnam_curve.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w_5JQnr-n3Db-XcYG6PJ7hPjVVmAHlPE
"""

# Commented out IPython magic to ensure Python compatibility.
import math
import matplotlib.pyplot as plt
# %matplotlib inline

def Putnam(k,t,ch):
  if ch==1:
    return(2*pow(k,1/3)*pow(t,4/3))
  elif ch==2:
    return(8*pow(k,1/3)*pow(t,4/3))
  elif ch==3:
    return(11*pow(k,1/3)*pow(t,4/3))
  else:
    print("Wromg choice given:")

def R_curve(k,td,t):
    project_duration=3*int(t)
    y=[round(Putnam(k,i,ch),5) for i in range(0, project_duration)]
    
    plt.plot(y, color="blue", linewidth=4, label="Effort respect to time")
    #plt.vlines(x=td,ymin=0,ymax=round(Putnam(k,t,ch),5),color="green", linestyle="dashed",linewidth=4,label=td)
    #plt.vlines(x=t,ymin=0,ymax=round(Putnam(k,t,ch),5),color="red",linestyle="dashed", linewidth=4,label="t")
    plt.legend(loc="upper right")
    plt.xlabel("time")
    plt.ylabel("Effort per unit time")
    plt.title("r_curve")
    plt.show()
  


#if _name_== "_main_":
print("norden formula")
k=float(input("Enter the value of effort :"))
t=float(input("Enter the development time...:"))
print("1.poor development...")
print("2.good development...")
print("3.Excellent development...")
print("Enter your choice:")
ch=int(input("enter your choice: "))
if ch==1:
    L=2*pow(k,1/3)*pow(t,4/3)
    print("The product size is ..",L,"KLOC")
elif ch==2:
    L=8*pow(k,1/3)*pow(t,4/3)
    print("The product size is ..",L,"KLOC")
elif ch==3:
    L=11*pow(k,1/3)*pow(t,4/3)
    print("The product size is ..",L,"KLOC")
else:
    print("Wromg choice given:")


print("required effort at time t, E--", round(Putnam(k,t,ch),5),"PM\n\n")
R_curve(k,t,L)

import matplotlib.pyplot as plt


def putnam(c0, k, td):
  return c0*pow(k,1/3)*pow(td,4/3)


def relay_graph(c0s, k, td):
    colors = {
        2: 'blue',
        8: 'black',
        11: 'red'
    }
    project_duration = 3 * int(td)
    for c0 in c0s:
      y = [round(putnam(c0, k, time), 5) for time in range(0, project_duration)]
      l = round(putnam(c0, k, td), 5)
      print(f"C0: {c0} | L: {l} KLOC")
      plt.plot(y, color=colors[c0], linewidth=4, label=f"c0: {c0} | l: {l}")
    
      plt.legend(loc="upper right")
      plt.xlabel("time") 
      plt.ylabel("product size")
      plt.title("r_curve for putnam")
      plt.show()


if __name__ == "__main__":
    print("###################   Putnam formula   ###################")
    k=float(input("Enter the value of effort :"))
    td=float(input("Enter the development time...:"))
    
    
    c0s = [2, 8, 11]
    relay_graph(c0s, k, td)